### ISSUE TITLE
Wanna merge and stuff?

### ISSUE THREAD

**Issue by TylerBrinks** [HockeyJustin/ExCSS_WithPullRequestsIncluded#16]
Hi @HockeyJustin,

I've had occasion to resurrect ExCSS and I've done so incorporating all the work you've done to date.  Are you interested in collaborating and unifying back to 1 repository & NuGet package?  I have a handful of changes that are slated and it might make sense to ... "un-fork?"  Whatever that means

**Comment by JsAndDotNet** [comment]
Hi @TylerBrinks. 

Thanks for getting in touch.

Definitely happy to collaborate on unifying back to 1 repo. Sounds like you've done the hard work :smiley:.

Please let me know how you wish to proceed.

**Comment by TylerBrinks** [comment]
Would it make sense to duplicate active issues to keep track of things?

**Comment by JsAndDotNet** [comment]
I didn't realise how time has flown! Thought I was keeping this thing up to date!

There are a couple of outstanding issues [13](https://github.com/HockeyJustin/ExCSS_Core/issues/13), [15](https://github.com/HockeyJustin/ExCSS_Core/issues/15)....

and a couple of fairly simple looking PR's [11](https://github.com/HockeyJustin/ExCSS_Core/pull/11), [14](https://github.com/HockeyJustin/ExCSS_Core/pull/14).

We could duplicate them, but if it's easier, I can try to bash through them over the next week or so to clear this repo, then you can merge that in if you're happy with it? Can't guarantee a timeline at the moment as work is crazy, but I'm hoping next week will be ok.

.NET 5 should be shipping soon - either 10th or 22nd at [.NET Conf](https://www.dotnetconf.net/). Will make sure it works on that too.

**Comment by TylerBrinks** [comment]
Fantastic on all fronts!  Thanks again!

________________________________

**Comment by JsAndDotNet** [comment]
Sorry. I haven't forgotten about this. Working long days at the moment. Will definitely get onto it soon though.

**Comment by JsAndDotNet** [comment]
@TylerBrinks - I have put a deprecation notice on ExCSS_Core, with reference to your new updated package. 

<img width="667" alt="EXCSS2" src="https://user-images.githubusercontent.com/4604271/100514629-5d839480-316e-11eb-90b8-edb57dbcdeea.PNG">


I had a look at your latest updates and it seems to include everything required. I see you've even updated for net5.0.

Is there anything else reqiured here, or can we close this (and ExCSS_Core)?

**Comment by TylerBrinks** [comment]
Thanks a ton!  I think that's good to go at this point.
