### ISSUE TITLE
Nuget package does not contain license information

### ISSUE THREAD

**Issue by paulvancoller** [HockeyJustin/ExCSS_WithPullRequestsIncluded#7]
The Nuget package does not contain license information.

This is needed for Fossa license compatibility scan:

![image](https://user-images.githubusercontent.com/52648234/70324024-0edf3b00-1837-11ea-8ce1-42d7a4a4ca4b.png)

**Comment by JsAndDotNet** [comment]
@paulvancoller-adeptadvisory . Ok, thanks. I'll look into it. Will keep this ticket open until it's done. 

Have a pretty rammed schedule so might be early next year, but will do it sooner if possible.

**Comment by paulvancoller** [comment]
Thanks @HockeyJustin. I would be more than happy to assist with this if the package source is available?

**Comment by JsAndDotNet** [comment]
Thanks @paulvancoller-adeptadvisory . I'll have a look at what's required.

**Comment by JsAndDotNet** [comment]
@paulvancoller-adeptadvisory . [Nuget package](https://www.nuget.org/packages/ExCSS-Core/) now includes MIT licence. 

Thanks for raising this issue.
